### ISSUE TITLE
Remove view.js?

### ISSUE THREAD

**Issue by GA-MEB** [ga-wdi-boston/ember-routing-dynamic#1]

**Comment by jrhorn424** [comment]
Generally in favor, but could you fill in context when you have a moment? I think it had to do with the fact that going with components this week has worked better than expected.

**Comment by GA-MEB** [comment]
You're right, I should definitely have left more notes - that issue is very unhelpful as-written.

I think what I meant was that the lesson didn't involve Views at all, and that it might make sense to simply take out the `view.js` file so that we can eliminate a dependency, in case we want to teach advanced routing before Views next time.

**Comment by jrhorn424** [comment]
I belive this is addressed. @MattB-GA-Boston

**Comment by GA-MEB** [comment]
@jrhorn424 Yeah, since we're not teaching Views at all anymore, the issues is resolved. The `view.js` file itself is still there, though, so I'll leave this issue open as a note to remove it eventually.

**Comment by jrhorn424** [comment]
Thanks @MattB-GA-Boston!

**Comment by raq929** [comment]
It looks like `view.js` has been removed.
