### ISSUE TITLE
Nested routes mean nested templates; `products` and `product` should be siblings.

### ISSUE THREAD

**Issue by GA-MEB** [ga-wdi-boston/ember-routing-dynamic#12]
Unless otherwise required by the UI, of course.

**Comment by jrhorn424** [comment]
Thanks @MattB-GA-Boston. As a reminder to myself, with nested routes for showing product will end up showing the product collection template **and** the product detail template (both `app/products/template.hbs` and `app/products/product/template.hbs`).

**Comment by laurenfazah** [comment]
Fixed for 011 if you'd like to close @MattB-GA-Boston @jrhorn424

**Comment by jrhorn424** [comment]
How do I confirm this is fixed? I don't see a solution for 11 and the demo was for 10.

**Comment by raq929** [comment]
This is fixed in the README instructions, IMO.

**Comment by raq929** [comment]
The instructions in the README seem clear at this point. @jrhorn424 says I can close.
