### ISSUE TITLE
Change references to 'ember-template' throughout the application

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/ember-routing-dynamic#14]
`ember-routing-dynamic`

**Comment by laurenfazah** [comment]
All set if you'd like to close @jrhorn424

**Comment by jrhorn424** [comment]
Thanks!

**Comment by jrhorn424** [comment]
All names should be `ga-wdi-boston.ember-routing-dynamic`. No slashes. Must prefix.

Except for the page title, of course.
