### ISSUE TITLE
Add "You Do" activities based on Orders (mirroring Products)

### ISSUE THREAD

**Issue by GA-MEB** [ga-wdi-boston/ember-routing-dynamic#3]
```
{
  id: 1,
  orderDate: '2015-12-01',
  totalCost: 50,
  purchaser: 'Petsi Pies'
}
```

**Comment by jrhorn424** [comment]
I chose to go with enhancing the employee team pages (making them dynamic instead of static). Does that address this issue @MattB-GA-Boston?

**Comment by GA-MEB** [comment]
@jrhorn424 Yep, that works. Closing the issue.
